name: Deploy Static Site to GitHub Pages and Daily Code Check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight (UTC) every day

jobs:
  deploy:
    if: github.event_name == 'push'  # Only run deploy on push events
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint

      - name: Build project
        run: echo "Build step goes here"  # Replace with actual build commands if needed

      - name: Run HTML and CSS validation
        run: |
          htmlhint **/*.html
          stylelint "**/*.css"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/ # or the directory containing your HTML/CSS files

  check_code:
    if: github.event_name == 'schedule'  # Only run code check on schedule events
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint

      - name: Run HTML and CSS validation
        run: |
          htmlhint **/*.html
          stylelint "**/*.css"
