name: Deploy Static Site to GitHub Pages and Daily Code Check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight (UTC) every day

jobs:
  deploy:
    if: github.event_name == 'push'  # Only run deploy on push events
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # or the version of Ruby you need

      - name: Install dependencies
        run: bundle install

      - name: Build project
        run: bundle exec jekyll build

      - name: Run tests
        run: |
          # Run HTML and CSS validation tests
          npm install -g htmlhint stylelint
          htmlhint **/*.html
          stylelint "**/*.css"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # Jekyll output directory

  check_code:
    if: github.event_name == 'schedule'  # Only run code check on schedule events
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Run HTML and CSS validation tests
          npm install -g htmlhint stylelint
          htmlhint **/*.html
          stylelint "**/*.css"
